// Articles
export const ARTICLES_FETCH_SUCCESS = 'ARTICLES_FETCH_SUCCESS'
export const ARTICLES_PICK_SUCCESS = 'ARTICLES_PICK_SUCCESS'

// User
export const USER_SET_TOKEN = 'USER_SET_TOKEN'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

// Pick
export const PICK_ARTILCE_SELECT = 'PICK_ARTILCE_SELECT'
export const PICK_ARTILCE_SUCCESS = 'PICK_ARTILCE_SUCCESS'

// Comments
export const COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS'
