// Articles
export const ARTICLES_FETCH_SUCCESS = 'ARTICLES_FETCH_SUCCESS'
export const ARTICLES_PICK_SUCCESS = 'ARTICLES_PICK_SUCCESS'

// User
export const USER_SET_TOKEN = 'USER_SET_TOKEN'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'
